version: '3.9'

services:
  mongodb:
    image: mongo:latest

  mongo-express:
    image: mongo-express:1.0-18
    depends_on:
    - mongodb

  rabbitmq:
    image: rabbitmq:4-management

  redis:
    image: redis:latest

  webapi:
    image: ${DOCKER_REGISTRY-}tsa-submissions-coding-webapi
    build:
      context: .
      dockerfile: ../Tsa.Submissions.Coding.WebApi/Dockerfile
    depends_on:
    - rabbitmq
    - redis
    - mongodb