version: '3.9'

services:
  mongodb:
    hostname: mongodb.tsa.localdev.me
    environment:
      MONGO_INITDB_DATABASE: submissions
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rIMdEnfnHj395cFO
    ports:
      - 27017:27017
    volumes:
      - ../docker/mongodb:/docker-entrypoint-initdb.d

  mongo-express:
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rIMdEnfnHj395cFO
      ME_CONFIG_MONGODB_SERVER: mongodb.tsa.localdev.me
    ports:
      - 8081:8081

  rabbitmq:
    ports:
      - 5672:5672
      - 8080:8080
      - 15672:15672

  redis:
    hostname: redis.tsa.localdev.me
    ports:
    - "6379:6379"

  webapi:
    hostname: api.tsa.localdev.me
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOCKER_CONTAINER: "Y"
    expose:
      - "8080"
    ports:
      - "80:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
